### PR TITLE
Add TS.REVRANGE and TS.MREVRANGE commands

### PR DESCRIPTION
**Pull request by cjdsellers**

### CODE REVIEW

**Comment by cjdsellers** [comment]
Are there any changes I may need to make before this could be merged?

**Comment by cjdsellers** [comment]
OK, all good points. Leave it with me.

**Comment by cjdsellers** [comment]
As requested above

**Review by DvirDukhan — APPROVED** [review]

**Comment by DvirDukhan** [comment]
@cjdsellers 
thanks for the PR

**Pull request merged**
